### ISSUE TITLE
tabBarOnPress passes wrong navigation prop

### ISSUE THREAD

**Issue by gzzo** [react-navigation/tabs#124]
### Current behaviour

tabBarOnPress passes the wrong navigation prop. If I pass the following to a screen in a tab navigator:

```
tabBarOnPress: ({ navigation }) => {
  console.log(navigation.state)
}
```

The state is *not* the current state of the navigator, but rather the future state assuming that `tabBarOnPress` eventually navigates to the pressed tab.

### Expected behaviour

I expect `navigation.state` to be the *current* state of the navigation.

### Code sample

https://snack.expo.io/H1z5jdyn4

This is clear from here: https://github.com/react-navigation/tabs/blob/master/src/utils/createTabNavigator.js#L121

### Proposed solution

I'm happy to provide a PR for this issue. Ideally I would want to preserve backwards compatibility, so I propose to provide a new `currentState` object that's passed to `tabBarOnPress` that comes from `this.props.navigation.state`

**Comment by gzzo** [comment]
I think this is still an issue to consider

**Comment by gzzo** [comment]
@satya164 Can we reopen this?

**Comment by satya164** [comment]
Not sure what you mean by:

> The state is not the current state of the navigator, but rather the future state assuming that tabBarOnPress eventually navigates to the pressed tab.

The `navigation` object passed is the same navigation object passed to the corresponding screen. We shouldn't actually be passing a navigation object here because you already get that if you make `navigationOptions` a function. It's just there because it was added by mistake and removing it will be a breaking change.

In your PR, you're passing `this.props.navigation.state`, which is the `navigation.state` object of the navigator. You can already access it with `navigation.dangerouslyGetParent().state` everywhere you get the navigation prop.

**Comment by gzzo** [comment]
Thanks!

> The state is not the current state of the navigator, but rather the future state assuming that tabBarOnPress eventually navigates to the pressed tab.

We have a use case for not navigating when a tab is pressed and instead performing another action. The `navigation.state` passed in `tabBarOnPress` is the state that you would have if you navigated to the screen.

I wasn't aware of `dangerouslyGetParent().state`, I think this should do the trick, thanks again!
