### ISSUE TITLE
How to animate hiding/showing of tab bar?

### ISSUE THREAD

**Issue by kennym** [react-navigation/tabs#129]
I've posted the question on StackOverflow: https://stackoverflow.com/questions/56171780/how-to-animate-hiding-showing-of-tab-bar

If you prefer to ask here, please let me know... I was just hoping someone could give me a hint on how to go about this.

**Comment by kennym** [comment]
Anyone?

**Comment by osdnk** [comment]
Can you confirm is it still an issue? Or share some snippets?

**Comment by adamsaint** [comment]
This is still an issue for me at least. For example, I have a StackNavigator that has a nested screen where it's necessary to hide the tab bar so that other UI can be rendered in its place. I can hide the tab bar just fine, e.g:

```
HomeStack.navigationOptions = ({ navigation }) => {
	let { routeName } = navigation.state.routes[navigation.state.index];
	let navigationOptions = {
		tabBarLabel: 'Practice',
		tabBarIcon: ({ focused }) => (
			<TabBarIcon
				focused={focused}
				name='brain'
			/>
		)
	};
	if (routeName === 'Practice') {
		navigationOptions.tabBarVisible = false;
	}
	return navigationOptions;
};
```

But I can't find a way (from the docs or on my own) to add an animated transition to the change in tabBarVisible. It _works_, but the transition is jarring and would look and feel much nicer if I could control its in/out behaviour.

**Comment by kennym** [comment]
Yes, this issue still persists

**Comment by roman-myshchyshyn** [comment]
Still persists.
