### ISSUE TITLE
transparent color of BottomTabNavigator not working.

### ISSUE THREAD

**Issue by mukeshsharma1201** [react-navigation/tabs#184]
### Current behaviour
Setting tabBarOptions.style.backgroundColor to transparent sets the background color to White.

### Expected behaviour
Setting tabBarOptions.style.backgroundColor to transparent should make the color invisible, i.e make the color transparent.

### Code sample
```javascript
createBottomTabNavigator(
    {
      DashboardStack: DashboardStack,
      EditStack: EditStack,
    },
    {
      tabBarOptions: {
        style: {
          backgroundColor: 'transparent',
        },
      },
    },
  ),
```

### What have you tried
I have tried the solution mentioned in a similar issue #46 but the problem with it is that other scrollView don't consider the tab bar as bottom anymore. That is, if I scroll my vertical scroll view to the very end, goes behind the tab bar.
<br>Scroll View looks like this after scrolling to the bottom: 
![Scroll View looks like this](https://i.imgur.com/0zIzko0.png)
<br>and on **Android** I am not able to change tabs using this method.

 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |both
| react-native          |0.60.5
| react-navigation-tabs |2.5.3
| node                  |v12.9.1
| npm or yarn           |6.10.2

**Comment by mukeshsharma1201** [comment]
Am I the only person who is facing this issue??

**Comment by tamurhaq** [comment]
> Am I the only person who is facing this issue??

Facing the same issue.

**Comment by adrianha** [comment]
just checked on this issue. `TabBar` should be displayed as `absolute` in order to render it above the content. But, adding `absolute` to `TabBar` will raise problem like @mukeshsharma1201 said that screen isn't aware `TabBar` anymore. any suggestion on this problem @osdnk @satya164 ? Do you think expose `onLayout` from `TabBar` to get height will be good solution for this? but using this approach, user will need to adjust each screen and adding padding based on `TabBar` height
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-15 at 02 04 27](https://user-images.githubusercontent.com/5382429/66776224-28779c80-eef0-11e9-8c6e-2756c25eda42.png)

**Comment by satya164** [comment]
@adrianha we can export something like `TabBarHeightContext` which user can use to get the height of the tab bar inside of a screen.

**Comment by samchamberland** [comment]
Let me know if you were still interested at looking at this @adrianha 👍 

If not, I'd gladly work on this.

**Comment by adrianha** [comment]
hi @samchamberland , you can try to solve this issue
