### ISSUE TITLE
tabBarOnPress doest not work on Android - defaultHandler is always called

### ISSUE THREAD

**Issue by Aure77** [react-navigation/tabs#202]
### Current behaviour

On Android only, when _tabBarOnPress_ is defined on a tab screen, without invoking _defaultHandler_ explicitly, it always call the default behavior (tab switching + highlight). _tabBarOnPress_  is not invoked too.
But that works on iOS...

### Expected behaviour

When _tabBarOnPress_ is defined on a tab screen, it should override default press behavior on both iOS and Android...

### Code sample

```
createBottomTabNavigator({
  Album: { screen: View },
  Library: { screen: View },
  History: {
    screen: View,
    navigationOptions: {
      tabBarOnPress: () => {
        alert("only working on iOS !");
      }
    }
  },
  Cart: { screen: View }
});
```

### What have you tried

I am already using latest version...

### Your Environment

| software              | version
| --------------------- | -------
| android        | 10
| react-native          | 0.61.2
| react-navigation-tabs | 2.5.6
| node                  | 10.16.1
| npm or yarn           | yarn

**Comment by SmirnovM91** [comment]
+1

**Comment by marqroldan** [comment]
Have you tried using console.log to see if it actually overrides the effect? I can't reproduce your problem but I am having troubles triggering the Alert on Android (9+)

**Comment by vfa-namth** [comment]
The same

**Comment by GitHubTracey** [comment]
I find on Android, it will only call the tabBarOnPress for a particular screen once... and then after that, it doesn't fire again. In my case I have a couple of stacks and a couple that are not stacks. It will navigate to the correct screen, but I have intentional interruptions for some screens - say not navigating away from an edit screen before the user has a chance to confirm they wish to navigate away and lose changes...  on Android, I currently cannot interrupt those actions.

**Comment by Aure77** [comment]
I think I found why there is this strange behaviour on Android. I think it due to `tabBarOnLongPress` default handler that is called. If I override both `tabBarOnLongPress` and `tabBarOnPress`, it seems working as expected.

**Comment by GitHubTracey** [comment]
@Aure77 wow. I didn't actually realize there was an tabBarOnLongPress. That fixed it for me. Thank-you so much!!
