### ISSUE TITLE
Proposal: Ability to pass params for tabBarOnPress defaultHandler function

### ISSUE THREAD

**Issue by rafalolszewski94** [react-navigation/tabs#229]
I'd expect that underneath `defaultHandler()` function in `navigationOptions > tabBarOnPress` of bottom tab navigator, it runs `navigate` function (I may be wrong), but great addition would be to pass some params for those tabs; for example:

```js
const MyNavigator = createBottomTabNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: () => ({
        tabBarOnPress: ({ navigation, defaultHandler }) => {
          defaultHandler({ foo: 'bar' });
        },
      }),
    },
  },
);
```

**Comment by rafalolszewski94** [comment]
You can currently do `navigation.setParams({ foo: 'bar' });` before `defaultHandler(...)` which gives the wanted result, but is that clean?

**Comment by satya164** [comment]
`defaultHandler` does a different things based on whether the tab was focused or not, e.g. pop stack to top, scroll to top, navigate etc. So passing params won't make sense in many of these cases.

If you want to set some params, you can call `navigate` yourself with params instead of using default handler.
